apiVersion: 1

datasources:
  - name: RocketMQ OTel Prometheus
    uid: rocketmq-otel-prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: false
    editable: false
  - name: RocketMQ OTel Tempo
    uid: rocketmq-otel-tempo
    type: tempo
    access: proxy
    url: http://127.0.0.1:3200
    isDefault: false
    editable: false
