services:
  volume-init:
    volumes:
      - ./data/nameserver-logs:/volumes/nameserver
      - ./data/broker-logs:/volumes/broker-logs
      - ./data/broker-store:/volumes/broker-store

  nameserver:
    volumes:
      - ./data/nameserver-logs:/home/rocketmq/logs

  broker:
    volumes:
      - ./data/broker-store:/home/rocketmq/store
      - ./data/broker-logs:/home/rocketmq/logs
